image: nixos/latest
sources:
  - https://git.sr.ht/~stfn/vegan-prestwich
secrets:
  - ff7f6e84-35b9-4aa9-afa1-1fbc3fe6a2d1 # ~/.neocities/vegan-prestwich
tasks:
  - build: |
      cd vegan-prestwich
      sh bin/build
