image: alpine/edge
packages:
  - ruby-dev
  - npm
environment:
  repo: vegan-prestwich-11ty
sources:
  - https://git.sr.ht/~stfn/vegan-prestwich-11ty
secrets:
  - ce4927a1-3324-4048-9b2d-79a82c67256d # neocities
tasks:
  - setup: |
      cd $repo
      npm install
      sudo gem install --no-document neocities
  - build: |
      cd $repo
      npm run build
  - deploy: |
      cd $repo
      sh ./neocities-deploy $repo _site
