image: alpine/edge
packages:
  - ruby-dev
  - npm
environment:
  repo: vegan-prestwich
sources:
  - https://git.sr.ht/~stfn/vegan-prestwich
  - https://github.com/stefan-burke/build-scripts
secrets:
  - ff7f6e84-35b9-4aa9-afa1-1fbc3fe6a2d1 # ~/.neocities/$repo
tasks:
  - setup: |
      cd $repo
      npm install
  - build: |
      cd $repo
      npm run build
  - deploy: |
      cd $repo
      sudo sh ./build-scripts/neocities-deploy $repo _site
