image: nixos/latest
packages:
  - nixos.html-minifier
  - nixos.lightningcss
  - nixos.neocities-cli
  - nixos.nodejs
  - nixos.nodePackages_latest.npm
  - nixos.sass
environment:
  repo: vegan-prestwich
sources:
  - https://git.sr.ht/~stfn/vegan-prestwich
secrets:
  - ff7f6e84-35b9-4aa9-afa1-1fbc3fe6a2d1 # ~/.neocities/$repo
tasks:
  - build: |
      cd $repo
      mkdir -p _site/style
      sass style/style.scss _site/style/style.css
      lightningcss --minify --targets '> 0.25%, not IE 11' _site/style/*.css -o _site/style/*.css
      npx @11ty/eleventy
      html-minifier --input-dir _site --output-dir _site --collapse-whitespace --file-ext html
      set +x
      export NEOCITIES_API_KEY=$(cat /home/user/.neocities/vegan-prestwich)
      set -x
      neocities push --prune _site
