image: alpine/edge
packages:
  - npm
environment:
  repo: vegan-prestwich
sources:
  - https://git.sr.ht/~stfn/vegan-prestwich-11ty
secrets:
  - b56325c2-cd2c-4a22-b5e9-8c43db571721 # neocities
tasks:
  - setup: |
      cd $repo
      npm install
  - build: |
      cd $repo
      npm run build
  - deploy: |
      cd $repo
      sh ./deploy-neocities $repo _site
